version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - frontend-backend-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-backend-network

networks:
  frontend-backend-network:
